### ISSUE TITLE
Obsolete snapshots

### ISSUE THREAD

**Issue by sroettering** [nifty10m/yangying#37]
Jest can detect obsolete snapshots and delete them when updating snapshots.
This would be a nice feature for yangying as well.
Possible usecase: renaming tests. When renaming tests the snapshot file is not renamed and thus loses the connection to its test case.

**Comment by terribleherbst** [comment]
Implementation is not that easy. Jest stores all result in one file but yangying uses multiple files for multiple test. A deletion after suite might be possible but maybe it deletes to much content.

**Comment by terribleherbst** [comment]
The latest master contains a version which contains a `FileCleanupExtension` which deletes all obsolete SNAPSHOTS in UPDATE mode.
